<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    
    <link name="base_link">
    </link>
    
    <joint name="wall_joint_se" type="fixed">
        <parent link="base_link"/>
        <child link="wall_se"/>
        <origin xyz="${1.25} -${1.25} ${wall_height/2}" rpy="0 0 ${pi/4}"/>
    </joint>
    <link name="wall_se">
        <visual>
            <origin xyz="0 0 0"/>
            <geometry>
                <box size="${wall2_length} ${wall_thickness} ${wall_height}"/>
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
            <origin xyz="0 0 0"/>
            <geometry>
                <box size="${wall2_length} ${wall_thickness} ${wall_height}"/>
            </geometry>
         </collision>
        <xacro:inertial_box mass="${wall_mass}" x="${wall2_length}" y="${wall_thickness}" z="${wall_height}">
            <origin xyz="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <joint name="wall_joint_s" type="fixed">
        <parent link="base_link"/>
        <child link="wall_s"/>
        <origin xyz="0 -${wall_distance} ${doors_bottom/2}" rpy="0 0 0"/>
    </joint>
    <link name="wall_s">
        <visual>
            <origin xyz="0 0 0"/>
            <geometry>
                <box size="${wall_length} ${wall_thickness} ${doors_bottom}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <origin xyz="0 0 0"/>
            <geometry>
                <box size="${wall_length} ${wall_thickness} ${doors_bottom}"/>
            </geometry>
         </collision>
        <xacro:inertial_box mass="${wall_mass}" x="${wall_length}" y="${wall_thickness}" z="${doors_bottom}">
            <origin xyz="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <joint name="wall_joint_ne" type="fixed">
        <parent link="base_link"/>
        <child link="wall_ne"/>
        <origin xyz="${1.25} ${1.25} ${wall_height/2}" rpy="0 0 -${pi/4}"/>
    </joint>
    <link name="wall_ne">
        <visual>
            <origin xyz="0 0 0"/>
            <geometry>
                <box size="${wall2_length} ${wall_thickness} ${wall_height}"/>
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
            <origin xyz="0 0 0"/>
            <geometry>
                <box size="${wall2_length} ${wall_thickness} ${wall_height}"/>
            </geometry>
         </collision>
        <xacro:inertial_box mass="${wall_mass}" x="${wall2_length}" y="${wall_thickness}" z="${wall_height}">
            <origin xyz="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <joint name="wall_joint_sw" type="fixed">
        <parent link="base_link"/>
        <child link="wall_sw"/>
        <origin xyz="-${1.25} -${1.25} ${wall_height/2}" rpy="0 0 -${pi/4}"/>
    </joint>
    <link name="wall_sw">
        <visual>
            <origin xyz="0 0 0"/>
            <geometry>
                <box size="${wall2_length} ${wall_thickness} ${wall_height}"/>
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
            <origin xyz="0 0 0"/>
            <geometry>
                <box size="${wall2_length} ${wall_thickness} ${wall_height}"/>
            </geometry>
         </collision>
        <xacro:inertial_box mass="${wall_mass}" x="${wall2_length}" y="${wall_thickness}" z="${wall_height}">
            <origin xyz="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <joint name="wall_joint_nb" type="fixed">
        <parent link="base_link"/>
        <child link="wall_nb"/>
        <origin xyz="0 ${wall_distance} ${doorn_bottom/2}" rpy="0 0 0"/>
    </joint>
    <link name="wall_nb">
        <visual>
            <origin xyz="0 0 0"/>
            <geometry>
                <box size="${wall_length} ${wall_thickness} ${doorn_bottom}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <origin xyz="0 0 0"/>
            <geometry>
                <box size="${wall_length} ${wall_thickness} ${doorn_bottom}"/>
            </geometry>
         </collision>
        <xacro:inertial_box mass="${wall_mass}" x="${wall_length}" y="${wall_thickness}" z="${doorn_bottom}">
            <origin xyz="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <joint name="wall_joint_nt" type="fixed">
        <parent link="base_link"/>
        <child link="wall_nt"/>
        <origin xyz="0 ${wall_distance} ${(wall_height - doorn_height)/2 + doorn_height}" rpy="0 0 0"/>
    </joint>
    <link name="wall_nt">
        <visual>
            <origin xyz="0 0 0"/>
            <geometry>
                <box size="${wall_length} ${wall_thickness} ${wall_height - doorn_height}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <origin xyz="0 0 0"/>
            <geometry>
                <box size="${wall_length} ${wall_thickness} ${wall_height - doorn_height}"/>
            </geometry>
         </collision>
        <xacro:inertial_box mass="${wall_mass}" x="${wall_length}" y="${wall_thickness}" z="${wall_height - doorn_height}">
            <origin xyz="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <joint name="wall_joint_nw" type="fixed">
        <parent link="base_link"/>
        <child link="wall_nw"/>
        <origin xyz="-${1.25} ${1.25} ${wall_height/2}" rpy="0 0 ${pi/4}"/>
    </joint>
    <link name="wall_nw">
        <visual>
            <origin xyz="0 0 0"/>
            <geometry>
                <box size="${wall2_length} ${wall_thickness} ${wall_height}"/>
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
            <origin xyz="0 0 0"/>
            <geometry>
                <box size="${wall2_length} ${wall_thickness} ${wall_height}"/>
            </geometry>
         </collision>
        <xacro:inertial_box mass="${wall_mass}" x="${wall2_length}" y="${wall_thickness}" z="${wall_height}">
            <origin xyz="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <joint name="wall_joint_w" type="fixed">
        <parent link="base_link"/>
        <child link="wall_w"/>
        <origin xyz="-${wall_distance} 0 ${(wall_height - doorw_height)/2 + doorw_height}" rpy="0 0 ${pi/2}"/>
    </joint>
    <link name="wall_w">
        <visual>
            <origin xyz="0 0 0"/>
            <geometry>
                <box size="${wall_length} ${wall_thickness} ${wall_height - doorw_height}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <origin xyz="0 0 0"/>
            <geometry>
                <box size="${wall_length} ${wall_thickness} ${wall_height - doorw_height}"/>
            </geometry>
         </collision>
        <xacro:inertial_box mass="${wall_mass}" x="${wall_length}" y="${wall_thickness}" z="${wall_height - doorw_height}">
            <origin xyz="0 0 0"/>
        </xacro:inertial_box>
    </link>

</robot>
