<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >
    
    <joint name="laser_joint" type="fixed">
        <parent link="chassis"/>
        <child link="laser_frame"/>
        <origin xyz="0.1 0 ${chassis_height + lidar_height/2}" rpy="0 0 0"/>
    </joint>

    <link name="laser_frame">
            <visual>
                <geometry>
                    <cylinder radius="${lidar_radius}" length="${lidar_height}"/>
                </geometry>
                <material name="red"/>
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${lidar_radius}" length="${lidar_height}"/>
                </geometry>
            </collision>
            <xacro:inertial_cylinder mass="0.1" length="${lidar_height}" 
                radius="${lidar_radius}">
                <origin xyz="0 0 0" rpy="0 0 0"/>
            </xacro:inertial_cylinder>     
    </link>

    <gazebo reference="laser_frame">
        <sensor name='lidar' type='gpu_lidar'>"
            <pose relative_to='laser_frame'>0 0 0 0 0 0</pose>
            <topic>lidar</topic>
            <update_rate>10</update_rate>
            <ray>
                <scan>
                    <horizontal>
                        <samples>360</samples>
                        <resolution>1</resolution>
                        <min_angle>-${pi}</min_angle>
                        <max_angle>${pi}</max_angle>
                    </horizontal>
                    <vertical>
                        <samples>1</samples>
                        <resolution>0.01</resolution>
                        <min_angle>0</min_angle>
                        <max_angle>0</max_angle>
                    </vertical>
                </scan>
                <range>
                    <min>${lidar_radius}</min>
                    <max>10.0</max>
                    <resolution>0.01</resolution>
                </range>
            </ray>
            <always_on>1</always_on>
            <visualize>true</visualize>
        </sensor>
    </gazebo>
</robot>
