<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!--    base link which is empty-->
    <link name="base_link">
    </link>

    <!--    Chassis-->
    <!--    chassis joint which is of fixed type to base with an offset of -0.1-->
    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="${chassis_offset} 0 0"/>
    </joint>

    <!--    chassis link which is the is a square that is the main body of the robot
            describes its visual, collision and inertia-->
    <link name="chassis">
        <visual>
            <origin xyz="${chassis_width/2} 0 ${chassis_height/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${chassis_width} ${chassis_width} ${chassis_height}"/>
            </geometry>
            <material name="green"/>
        </visual>
        <collision>
            <origin xyz="${chassis_width/2} 0 ${chassis_height/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${chassis_width} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="${chassis_mass}" x="${chassis_width}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz="${chassis_width/2} 0 ${chassis_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>


    <!-- LEFT WHEEL -->
    <!--    Left wheel joint of type continuous can rotate continuously around al 360 degrees-->
    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel"/>
        <origin xyz="0 ${wheel_offset} 0" rpy="-${pi/2} 0 0"/>
        <axis xyz="0 0 1"/>
    </joint>

    <!--    Describing the visual, collision and inertia of the Left Wheel-->
    <link name="left_wheel">
        <visual>
            <geometry>
                <cylinder length="${wheel_length}" radius="${wheel_radius}" />
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <cylinder length="${wheel_length}" radius="${wheel_radius}" /> 
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_length}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <!-- RIGHT WHEEL -->
    <!--    Right wheel joint of type continuous can rotate continuously around al 360 degrees--> 
    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel"/>
        <origin xyz="0 -${wheel_offset} 0" rpy="${pi/2} 0 0"/>
        <axis xyz="0 0 -1"/>
    </joint>

    <!--    Describing the visual, collision and inertia of the Right Wheel-->
    <link name="right_wheel">
        <visual>
            <geometry>
                <cylinder length="${wheel_length}" radius="${wheel_radius}" />
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <cylinder length="${wheel_length}" radius="${wheel_radius}" /> 
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_length}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <!-- CASTER WHEEL -->
    <!--    Caster Wheel of joint type fixed-->
    <joint name="caster_wheel_joint" type="fixed">
        <parent link="chassis"/>
        <child link="caster_wheel"/>
        <origin xyz="${caster_wheel_offset} 0 0" rpy="0 0 0"/>
    </joint>

    <!--    Describing the Caster Wheel to be a sphere with its visual, collision and inertia-->
    <link name="caster_wheel">
        <visual>
            <geometry>
                <sphere radius="${caster_wheel_radius}" />
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${caster_wheel_radius}" /> 
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="${caster_wheel_mass}" radius="${caster_wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>



</robot>