<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro"  name="robot">
    <!-- This will include all the contents of example_include.xacro first -->
    <xacro:include filename="colors.xacro" />
    <xacro:include filename="inertial.xacro" />

    <!-- This first link called "world" is empty -->
    <link name="world"></link>

    <xacro:property name="gear1_thickness" value="0.1" />
    <xacro:property name="gear1_radius" value="1" />

    <joint name="gear1" type="continuous">
        <origin xyz="2 0 0" rpy="0 0 0"/>
        <parent link="world"/>
        <child link="gear1_link"/>
        <axis xyz="0 0 1"/>    
    </joint>

    <link name="gear1_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>                
                <cylinder length="${gear1_thickness}" radius="${gear1_radius}" />
            </geometry>
            <material name="white" />
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${gear1_thickness}" radius="${gear1_radius}" />
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="1.0" length="${gear1_thickness}"
            radius="${gear1_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>


    <xacro:property name="gear2_thickness" value="0.1" />
    <xacro:property name="gear2_radius" value="0.5" />

    <joint name="gear2" type="continuous">
        <origin xyz="-2 0 0" rpy="0 0 0"/>
        <parent link="world"/>
        <child link="gear2_link"/>
        <axis xyz="0 0 1"/>
        <mimic joint="gear1" multiplier="${gear1_radius/gear2_radius}" offset="0.0"/>    
    </joint>

    <link name="gear2_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>                
                <cylinder length="${gear2_thickness}" radius="${gear2_radius}" />
            </geometry>
            <material name="white" />
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${gear2_thickness}" radius="${gear2_radius}" />
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="1.0" length="${gear1_thickness}"
            radius="${gear1_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <joint name="marker1" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <parent link="gear1_link"/>
        <child link="marker1_link"/>
        <axis xyz="0 0 1"/>
    </joint>

    <xacro:property name="marker1_thickness" value="${gear1_thickness*1.1}"/>
    <xacro:property name="marker1_length" value="${gear1_radius}"/>

    <link name="marker1_link">
        <visual>
            <origin xyz="${marker1_length/2} 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>
                <box size="${marker1_thickness} ${marker1_thickness} ${marker1_length}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <origin xyz="${marker1_length/2} 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>
                <box size="${marker1_thickness} ${marker1_thickness} ${marker1_length}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.1" x="${marker1_thickness/2}" y="${marker1_thickness/2}" z="${marker1_length/2}">
            <origin xyz="${marker1_length/2} 0 0" rpy="0 ${pi/2} 0"/>
        </xacro:inertial_box>
    </link>

    <joint name="marker2" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <parent link="gear2_link"/>
        <child link="marker2_link"/>
        <axis xyz="0 0 1"/>
    </joint>

    <xacro:property name="marker2_thickness" value="${gear2_thickness*1.1}"/>
    <xacro:property name="marker2_length" value="${gear2_radius}"/>

    <link name="marker2_link">
        <visual>
            <origin xyz="${marker2_length/2} 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>
                <box size="${marker2_thickness} ${marker2_thickness} ${marker2_length}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <origin xyz="${marker2_length/2} 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>
                <box size="${marker2_thickness} ${marker2_thickness} ${marker2_length}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.1" x="${marker2_thickness/2}" y="${marker2_thickness/2}" z="${marker2_length/2}">
            <origin xyz="${marker2_length/2} 0 0" rpy="0 ${pi/2} 0"/>
        </xacro:inertial_box>
    </link>

</robot>
